name: TypeScript Smoke Test
on:
    push:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 24.x
                  cache: npm

            - name: Install NPM dependencies
              run: npm ci && cd test/typescript && npm install

            - name: Compile TypeScript sources
              run: cd test/typescript && npm run compile
